sudo: false
language: node_js
script:
  - yarn install
  - yarn run bootstrap
  - yarn run lint
  - cd modules/core/
  - npm run build
  - cd ../cmpapi/
  - npm run build
after_success:
  - npm run upload:lcov
