version: 2.1
jobs:
  build:
    docker:
      - image: 'circleci/node:10.15.3'
    steps:
      - checkout
      - run: yarn
      - run: yarn build
      - run: yarn add -D mocha-junit-reporter
      - run: mkdir ~/junit
      - run:
          command: yarn test --reporter mocha-junit-reporter
          environment:
            MOCHA_FILE: ~/junit/test-results.xml
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
